version: "3.9"
services:
  shorturl: 
    container_name: shorturl
    build: .
    ports: 
      - 3000:3000
      - 50051:50051
    restart: no
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shorturl-net
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      PGUSER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 2
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}"
    restart: no
    networks:
      - shorturl-net

volumes:
  pg-data:

networks:
  shorturl-net:
    driver: bridge