// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.3
// source: api/v1/shorturl/urls.proto

package shorturlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OgUrl string `protobuf:"bytes,1,opt,name=ogUrl,proto3" json:"ogUrl,omitempty"`
}

func (x *PostUrlRequest) Reset() {
	*x = PostUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_shorturl_urls_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUrlRequest) ProtoMessage() {}

func (x *PostUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_shorturl_urls_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUrlRequest.ProtoReflect.Descriptor instead.
func (*PostUrlRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_shorturl_urls_proto_rawDescGZIP(), []int{0}
}

func (x *PostUrlRequest) GetOgUrl() string {
	if x != nil {
		return x.OgUrl
	}
	return ""
}

type PostUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortLink string `protobuf:"bytes,1,opt,name=shortLink,proto3" json:"shortLink,omitempty"`
}

func (x *PostUrlResponse) Reset() {
	*x = PostUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_shorturl_urls_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUrlResponse) ProtoMessage() {}

func (x *PostUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_shorturl_urls_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUrlResponse.ProtoReflect.Descriptor instead.
func (*PostUrlResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_shorturl_urls_proto_rawDescGZIP(), []int{1}
}

func (x *PostUrlResponse) GetShortLink() string {
	if x != nil {
		return x.ShortLink
	}
	return ""
}

type GetUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortLink string `protobuf:"bytes,1,opt,name=shortLink,proto3" json:"shortLink,omitempty"`
}

func (x *GetUrlRequest) Reset() {
	*x = GetUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_shorturl_urls_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUrlRequest) ProtoMessage() {}

func (x *GetUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_shorturl_urls_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUrlRequest.ProtoReflect.Descriptor instead.
func (*GetUrlRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_shorturl_urls_proto_rawDescGZIP(), []int{2}
}

func (x *GetUrlRequest) GetShortLink() string {
	if x != nil {
		return x.ShortLink
	}
	return ""
}

type GetUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OgUrl string `protobuf:"bytes,1,opt,name=ogUrl,proto3" json:"ogUrl,omitempty"`
}

func (x *GetUrlResponse) Reset() {
	*x = GetUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_shorturl_urls_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUrlResponse) ProtoMessage() {}

func (x *GetUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_shorturl_urls_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUrlResponse.ProtoReflect.Descriptor instead.
func (*GetUrlResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_shorturl_urls_proto_rawDescGZIP(), []int{3}
}

func (x *GetUrlResponse) GetOgUrl() string {
	if x != nil {
		return x.OgUrl
	}
	return ""
}

var File_api_v1_shorturl_urls_proto protoreflect.FileDescriptor

var file_api_v1_shorturl_urls_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72,
	0x6c, 0x2f, 0x75, 0x72, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x22, 0x26, 0x0a, 0x0e, 0x50, 0x6f, 0x73, 0x74, 0x55, 0x72,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x67, 0x55, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x67, 0x55, 0x72, 0x6c, 0x22, 0x2f,
	0x0a, 0x0f, 0x50, 0x6f, 0x73, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x22,
	0x2d, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x26,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x6f, 0x67, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6f, 0x67, 0x55, 0x72, 0x6c, 0x32, 0x8c, 0x01, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x55, 0x72, 0x6c, 0x12, 0x40, 0x0a, 0x07, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x12, 0x18,
	0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x55, 0x72,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x75, 0x72, 0x6c, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x07, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65,
	0x12, 0x17, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x55,
	0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x75, 0x72, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x75, 0x72, 0x6c, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_shorturl_urls_proto_rawDescOnce sync.Once
	file_api_v1_shorturl_urls_proto_rawDescData = file_api_v1_shorturl_urls_proto_rawDesc
)

func file_api_v1_shorturl_urls_proto_rawDescGZIP() []byte {
	file_api_v1_shorturl_urls_proto_rawDescOnce.Do(func() {
		file_api_v1_shorturl_urls_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_shorturl_urls_proto_rawDescData)
	})
	return file_api_v1_shorturl_urls_proto_rawDescData
}

var file_api_v1_shorturl_urls_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_v1_shorturl_urls_proto_goTypes = []interface{}{
	(*PostUrlRequest)(nil),  // 0: shorturl.PostUrlRequest
	(*PostUrlResponse)(nil), // 1: shorturl.PostUrlResponse
	(*GetUrlRequest)(nil),   // 2: shorturl.GetUrlRequest
	(*GetUrlResponse)(nil),  // 3: shorturl.GetUrlResponse
}
var file_api_v1_shorturl_urls_proto_depIdxs = []int32{
	0, // 0: shorturl.ShortUrl.Shorten:input_type -> shorturl.PostUrlRequest
	2, // 1: shorturl.ShortUrl.Reverse:input_type -> shorturl.GetUrlRequest
	1, // 2: shorturl.ShortUrl.Shorten:output_type -> shorturl.PostUrlResponse
	3, // 3: shorturl.ShortUrl.Reverse:output_type -> shorturl.GetUrlResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_shorturl_urls_proto_init() }
func file_api_v1_shorturl_urls_proto_init() {
	if File_api_v1_shorturl_urls_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_shorturl_urls_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_shorturl_urls_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_shorturl_urls_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_shorturl_urls_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_shorturl_urls_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_shorturl_urls_proto_goTypes,
		DependencyIndexes: file_api_v1_shorturl_urls_proto_depIdxs,
		MessageInfos:      file_api_v1_shorturl_urls_proto_msgTypes,
	}.Build()
	File_api_v1_shorturl_urls_proto = out.File
	file_api_v1_shorturl_urls_proto_rawDesc = nil
	file_api_v1_shorturl_urls_proto_goTypes = nil
	file_api_v1_shorturl_urls_proto_depIdxs = nil
}
